### ISSUE TITLE
sendMessage work only once

### ISSUE THREAD

**Issue by zartosht** [nksmnf/nestjs-telegram#328]
there is a problem in sending messages, if you use sendMessaage for once, it work ok and fine but if you try that for second time in the same response such as:

```
.. SOME‌CALCULATIONS...
await this.telegram.sendMessage({
      chat_id: message.chat.id,
      text: 'MESSAGE',
      parse_mode: 'markdown',
});
.. SOMEOTHER‌CALCULATIONS...
await this.telegram.sendMessage({ <-- this call will be ignored!
      chat_id: message.chat.id,
      text: 'ANOTHER_MESSAGE',
      parse_mode: 'markdown',
    });
```

also if you could handle long messages to split them and send them in order would be nice.

thanks.

**Comment by evilsprut** [comment]
@zartosht `sendMessage` method returns `Observable`, not `Promise`. You cannot use `await` on `Observable`, but you can add `.toPromise()` after `sendMessage()` if you want to use await.

```typescript
// .. SOME‌CALCULATIONS...
await this.telegram.sendMessage({
      chat_id: message.chat.id,
      text: 'MESSAGE',
      parse_mode: 'markdown',
}).toPromise();
// .. SOMEOTHER‌CALCULATIONS...
await this.telegram.sendMessage({ <-- this call will be ignored!
      chat_id: message.chat.id,
      text: 'ANOTHER_MESSAGE',
      parse_mode: 'markdown',
}).toPromise();
```
That information also exist in readme.
